apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scalable-ue5-pipeline.fullname" . }}
  labels:
    app: {{ include "scalable-ue5-pipeline.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "scalable-ue5-pipeline.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "scalable-ue5-pipeline.name" . }}
    spec:
      containers:
        - name: ue5-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: LOG_LEVEL
              value: "{{ .Values.env.LOG_LEVEL }}"
            - name: UE_MODE
              value: "{{ .Values.env.UE_MODE }}"
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
