apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unreal-devops.fullname" . }}
  labels:
    app: {{ include "unreal-devops.name" . }}
    chart: {{ include "unreal-devops.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "unreal-devops.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
      labels:
        app: {{ include "unreal-devops.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
