replicaCount: 1

image:
  repository: ghcr.io/your-org-name/scalable-ue5-pipeline
  tag: dev
  pullPolicy: Always

env:
  LOG_LEVEL: debug
  UE_MODE: development

resources:
  limits:
    cpu: "1000m"
    memory: "1024Mi"
  requests:
    cpu: "500m"
    memory: "512Mi"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: dev.ue5.example.com
      paths:
        - path: /
          pathType: Prefix

observability:
  enabled: true
  prometheus: true
  grafana: false  # Can be toggled
