image:
  repository: ghcr.io/your-org/unreal-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

observability:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true