replicaCount: 3

image:
  repository: ghcr.io/your-org-name/scalable-ue5-pipeline
  tag: latest
  pullPolicy: IfNotPresent

env:
  LOG_LEVEL: warn
  UE_MODE: production

resources:
  limits:
    cpu: "2000m"
    memory: "4096Mi"
  requests:
    cpu: "1000m"
    memory: "2048Mi"

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: ue5.example.com
      paths:
        - path: /
          pathType: Prefix

observability:
  enabled: true
  prometheus: true
  grafana: true
