replicaCount: 2

image:
  repository: ghcr.io/your-org-name/scalable-ue5-pipeline
  tag: sit
  pullPolicy: Always

env:
  LOG_LEVEL: info
  UE_MODE: staging

resources:
  limits:
    cpu: "1500m"
    memory: "2048Mi"
  requests:
    cpu: "750m"
    memory: "1024Mi"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: sit.ue5.example.com
      paths:
        - path: /
          pathType: Prefix

observability:
  enabled: true
  prometheus: true
  grafana: true
