name: Deploy to Kubernetes via Helm

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, sit, prod]

    env:
      HELM_RELEASE_NAME: unreal-devops-app
      KUBE_CONFIG_DATA: ${{ secrets[format('KUBE_CONFIG_{0}', matrix.environment)] }}
      NAMESPACE: ${{ matrix.environment }}
      VALUES_FILE: helm/values-${{ matrix.environment }}.yaml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.12.0'

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Decode and write kubeconfig
        run: |
          echo "${KUBE_CONFIG_DATA}" | base64 -d > $HOME/.kube/config

      - name: Helm dependency update
        run: helm dependency update helm/

      - name: Helm upgrade or install
        run: |
          helm upgrade --install $HELM_RELEASE_NAME ./helm \
            --namespace $NAMESPACE \
            --create-namespace \
            -f $VALUES_FILE
