name: Deploy to Kubernetes via Helm

on:
  push:
    branches:
      - develop
      - sit
      - main # prod
    paths:
      - 'helm/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:
env:
  REGISTRY: ghcr.io/your-org-name
  IMAGE_NAME: scalable-ue5-pipeline
jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    name: Deploy to Dev Environment
    steps:
      - uses: actions/checkout@v4
      - name: Set up Kubernetes context
        run: |
          kubectl config use-context dev-cluster
      - name: Deploy using Helm
        run: |
          helm upgrade --install ue5-dev ./helm \
            -f ./helm/values-dev.yaml \
            --namespace ue5-dev \
            --create-namespace

  deploy-sit:
    if: github.ref == 'refs/heads/sit'
    runs-on: ubuntu-latest
    name: Deploy to SIT Environment
    steps:
      - uses: actions/checkout@v4
      - name: Set up Kubernetes context
        run: |
          kubectl config use-context sit-cluster
      - name: Deploy using Helm
        run: |
          helm upgrade --install ue5-sit ./helm \
            -f ./helm/values-sit.yaml \
            --namespace ue5-sit \
            --create-namespace

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy to Production Environment
    steps:
      - uses: actions/checkout@v4
      - name: Set up Kubernetes context
        run: |
          kubectl config use-context prod-cluster
      - name: Deploy using Helm
        run: |
          helm upgrade --install ue5-prod ./helm \
            -f ./helm/values-prod.yaml \
            --namespace ue5-prod \
            --create-namespace