name: Deploy to Kubernetes via Helm

on:
  push:
    branches:
      - develop
      - sit
      - main # prod
    paths:
      - 'helm/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:
env:
  REGISTRY: ghcr.io/your-org-name
  IMAGE_NAME: scalable-ue5-pipeline
jobs:

  # Step 1: Build
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ue5-build-image .
      
      - name: Notify Slack on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
          "text": "🚨 *Unreal Engine CI/CD Pipeline* failed on job `${{ github.job }}` in `${{ github.workflow }}`.\n🔗 <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>"
          }' $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  # Step 2: Automated Tests (Functional/Unit)
  test-functional:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Blueprint/Functional Tests
        run: |
          docker run --rm ue5-build-image ./run-tests.sh

      - name: Upload Functional Test Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: functional-test-results
          path: /app/Saved/Automation
      - name: Notify Slack on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
          "text": "🚨 *Unreal Engine CI/CD Pipeline* failed on job `${{ github.job }}` in `${{ github.workflow }}`.\n🔗 <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>"
          }' $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  test-multiplayer:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Gauntlet Multiplayer Tests
        run: |
          docker run --rm ue5-build-image \
            ./Engine/Build/BatchFiles/RunUAT.sh \
            RunUnrealTests -project=/app/MyGame.uproject \
            -test=SimpleJoinTest -clientcount=1 -servercount=1

      - name: Upload Gauntlet Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gauntlet-results
          path: /app/Saved/Logs
      
      - name: Notify Slack on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
          "text": "🚨 *Unreal Engine CI/CD Pipeline* failed on job `${{ github.job }}` in `${{ github.workflow }}`.\n🔗 <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>"
          }' $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

   # Step 4: Deploy to Dev (only if tests pass)
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    needs: [test-functional, test-multiplayer]
    runs-on: ubuntu-latest
    name: Deploy to Dev Environment
    steps:
      - uses: actions/checkout@v4
      - name: Set up Kubernetes context
        run: |
          kubectl config use-context dev-cluster
      - name: Deploy using Helm
        run: |
          helm upgrade --install ue5-dev ./helm \
            -f ./helm/values-dev.yaml \
            --namespace ue5-dev \
            --create-namespace

  # Step 5: Deploy to SIT
  deploy-sit:
    if: github.ref == 'refs/heads/sit'
    needs: [test-functional, test-multiplayer]
    runs-on: ubuntu-latest
    name: Deploy to SIT Environment
    steps:
      - uses: actions/checkout@v4
      - name: Set up Kubernetes context
        run: |
          kubectl config use-context sit-cluster
      - name: Deploy using Helm
        run: |
          helm upgrade --install ue5-sit ./helm \
            -f ./helm/values-sit.yaml \
            --namespace ue5-sit \
            --create-namespace

  # Step 6: Deploy to Production
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: [test-functional, test-multiplayer]
    runs-on: ubuntu-latest
    name: Deploy to Production Environment
    steps:
      - uses: actions/checkout@v4
      - name: Set up Kubernetes context
        run: |
          kubectl config use-context prod-cluster
      - name: Deploy using Helm
        run: |
          helm upgrade --install ue5-prod ./helm \
            -f ./helm/values-prod.yaml \
            --namespace ue5-prod \
            --create-namespace
   
  # Step 7: Notify Slack on failure deployment
  notify-failure:
    needs: [build, test-functional, test-multiplayer, deploy-dev, deploy-sit, deploy-prod]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack of CI/CD failure
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "🚨 *CI/CD Failure* on `${{ github.ref_name }}` branch. Check the run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>"
          }' $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
